chingu-voyages/V55-tier2-team-25

react-app/src/components/ClearButton.jsx, react-app/src/components/Footer.jsx, react-app/src/components/Header.jsx, react-app/src/components/SearchBar.jsx, react-app/src/components/SearchButton.jsx
- I removed the color from most component classes so it would use the global styles to change automatically with light/dark mode. 
- I used colors and added dark mode for buttons.
- I also added "Bar" to "Search Bar" (hidden) label for screen reader clarity.
=> Troubleshooting dark mode

react-app/src/components/Footer.jsx
updated padding to align with section above the footer. need to add James's info to the footer.
=> Wip footer molly

react-app/src/components/Footer.jsx
Molly, I added the changes here in this branch. I accidentally approved your changes before I pushed these changes up. Thank you!
=> reviewed and updated code with suggested changes

README.md
I added links for James to the ReadMe. In the future, I think we should work on deciding on a streamlined approach to names and titles.
=> Added links for James in the ReadMe

README.md, react-app/src/components/Footer.jsx
I added James to the app footer. In the future, I think we should work on deciding on a streamlined approach to names and titles.
=> Added James with links to the app footer

README.md, react-app/src/components/Footer.jsx, react-app/src/components/LatestSection.jsx, react-app/src/components/RecommendSection.jsx
I started the API integration with the "Latest" section. 
Note: To my understanding, we will also need some changes to the design, given we don't have an image or description in the API objects, as far as I can tell.
=> Began API integration with the "Latest" section

react-app/src/components/LatestSection.jsx
I added some comments to explain what you did in the code, and added console logs to check the api calls.
=> Wip latest marissa

react-app/package-lock.json, react-app/package.json, react-app/src/app/page.js, react-app/src/app/store.js, react-app/src/components/LatestSection.jsx, react-app/src/components/SearchBar.jsx, react-app/src/components/SearchButton.jsx, react-app/src/components/SearchResults.jsx, react-app/src/redux/dataSlice.js
Added API call to entire app using Redux
=> Wip search bar marissa

react-app/package-lock.json, react-app/package.json, react-app/src/components/LatestSection.jsx, react-app/src/components/ResourceItem.jsx
Separated ResourceItem so it can be re-used in the SearchResults and Random sections.
=> Separated ResourceItem and LatestSection, added Swiper, unable to format equal article heights

react-app/src/components/LatestSection.jsx, react-app/src/components/ResourceItem.jsx
Includes:
- Hyperlinks to resources (issue #11) by clicking anywhere on the card
- Revised date format
- An attempt to implement design spacing in a flexible, responsive way
- Did NOT implement colors
=> Revised resource item card styles to align with new design

react-app/src/components/Header.jsx
I couldn't get the webpage to load. This needs to be tested if it's working, but I wanted to push the changes for now so we don't get merge conflicts. I added the icon that MJ shared with us in the header of the app.
=> added logo for PeerPicks- needs to be tested

react-app/src/app/page.js, react-app/src/components/LatestSection.jsx, react-app/src/components/ResourceList.jsx, react-app/src/components/SearchContainer.jsx
Unfortunately, the "Latest" section also refreshes on each search submission. I tried to add isDataLoaded functionality to Redux, but it seems the use of useSelector with Redux might be preventing that from working, so I undid it. [Resource: Understanding useSelector: How to Access Redux Store State in React](https://www.dhiwise.com/post/useselector-how-to-access-redux-store-state-in-react)
=> Search now runs on button click

react-app/src/components/Filter.jsx, react-app/src/components/LatestSection.jsx, react-app/src/components/ResourceItem.jsx, react-app/src/components/ResourceList.jsx, react-app/src/components/SearchBar.jsx, react-app/src/components/SearchContainer.jsx, react-app/src/redux/dataSlice.js
Not yet styled, not yet functional
=> Started building filter menu

react-app/src/app/globals.css, react-app/src/components/Filter.jsx, react-app/src/components/Footer.jsx
Note: I commented out the dark color option in global styles for now
=> Some styling on filter menu

react-app/src/app/globals.css, react-app/src/app/page.js, react-app/src/components/ClearButton.jsx, react-app/src/components/Filter.jsx, react-app/src/components/SearchContainer.jsx, react-app/tailwind.config.js
added the grayed out background to the filter. I still need to work on graying out the tags. For some reason, they are appearing through the gray effect.
=> Wip filter style marissa

react-app/src/app/globals.css, react-app/src/components/SearchContainer.jsx
Added state to track when a search has or hasn't been performed. Added state to the function to check if searches were performed. If they were, and 0 results were found, the component would render the appropriate message.
=> Wip results marissa

react-app/src/components/Filter.jsx, react-app/src/components/SearchContainer.jsx
- Added logic for 1 result found
- Revised loading message so it isn't filter specific in phrasing (it is in the filter component)
=> Added logic for 1 result found and revised loading message

react-app/src/components/Results/ResourceItem.jsx
I realized I had the line clamp on the wrong div.
=> Resolved tag line clamp issue

react-app/src/components/Header.jsx
changes to padding, margin, layout for desktop
=> changes to styling for desktop header

react-app/src/components/SearchControl/Filter.jsx, react-app/src/components/SearchControl/SearchBar.jsx
this works when screen is set to full, but if it is adjusted width wise within desktop there is an issue. also adjusted search bar width
=> absolute positioning of filter icon

react-app/src/components/Footer.jsx
added James and messed with the tablet styles. Ill keep adjusting it later.
=> Added name and tablet style

react-app/src/components/MainContainer.jsx, react-app/src/components/SearchControl/Filter.jsx, react-app/src/components/SearchControl/SearchBar.jsx
changes to modal layout/sizing (color changes to assist with this)
=> Wip search molly
